version: 2.1

workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: stlouisn/ubuntu:latest
  steps:
    - setup_remote_docker:
        version: 20.10.11
    - run: docker version
    - checkout
    - run: docker buildx build . 