version: 2.1

jobs:
  build-container:
    resource_class: small
    environment:
      #C_DESCRIPTION: "ubuntu base image"   # <-- variable
      #C_MAINTAINER: "stlouisn"              # <-- variable
      # C_NAME: "ubuntu"                     # <-- variable
      # C_TAG: "latest"                      # <-- variable
      # BUILD_PLATFORMS: "linux/arm64,linux/arm/v7"
    docker:
      - image: cimg/base:stable
        auth:
          username: stlouisn
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Set Env
          #command: echo 'export C_MAINTAINER="stlouisn"' >> $BASH_ENV
          command: |
            cat environment >> $BASH_ENV
            export C_VERSION="$(bash scripts/get_version.sh)"
      - run:
          name: Test Env
          command: env | sort
      - run:
          name: Label dockerfile
          command: bash scripts/set_labels.sh
      - run:
          name: Preparing dockerfile
          command: |
            sed -i -e '/^$/d' -e 's/^[ \t]*//' -e '/^#/d' dockerfile
            cat dockerfile
      - run:
          name: Configure Docker Hub
          command: |
            [ -z "$DOCKER_PASSWORD" ] && exit 1
            echo "$DOCKER_PASSWORD" | docker login --username=stlouisn --password-stdin
      # - run:
      #     name: Configure Docker Buildx
      #     command: |
      #       docker buildx version
      #       echo
      #       sudo apt-get update -qq && sudo apt-get install -y binfmt-support qemu-user-static
      #       echo
      #       docker pull multiarch/qemu-user-static
      #       echo
      #       docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      #       echo
      #       docker context create buildcontext
      #       echo
      #       docker buildx create buildcontext --use --platform $BUILD_PLATFORMS
      # - run:
      #     name: Build and push container
      #     no_output_timeout: 20m
      #     command: |
      #       docker buildx inspect --bootstrap
      #       echo
      #       docker buildx build --tag stlouisn/$C_NAME:$C_TAG --platform $BUILD_PLATFORMS --progress plain --push .

workflows:
  version: 2
  build-container:
    jobs:
      - build-container
