version: 2.1

commands:

  configure-dockerhub:
    description: Configure Docker Hub access
    steps:
      - run:
          name: Configure Docker Hub
          command: |
            [ -z "$DOCKER_LOGIN" ] && exit 0
            [ -z "$DOCKER_PASSWORD" ] && exit 0
            docker login --username=$DOCKER_LOGIN --password=$DOCKER_PASSWORD

  install-docker-buildx:
    description: Install Docker Buildx
    steps:
      - run:
          name: Install Docker Buildx
          command: |
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx version
            sudo apt-get update && sudo apt-get install -y binfmt-support qemu-user-static
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker run --privileged --rm tonistiigi/binfmt --install arm64
            docker context create buildcontext
            docker buildx create buildcontext --use

jobs:
  build-multiarch-container:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - install-docker-buildx
      - configure-dockerhub
      - run:
          name: Build and push container
          no_output_timeout: 2h
          command: |
            docker buildx inspect --bootstrap
            docker buildx build --progress plain --push -t stlouisn/ubuntu --platform linux/amd64,linux/arm64,linux/arm .

workflows:
  version: 2
  build-images:
    jobs:
      - build-multiarch-container:
          name: build-python-base-arm64
          context:
            - dockerhub
            - models
          filters:
            branches:
              only:
                - main

# orbs:
#   docker-buildx: foodles/docker-buildx@0.0.3

# workflows:
#     build-deploy:
#       jobs:
#         - docker-buildx/publish:
#             dockerfile: dockerfile
#             image: stlouisn/ubuntu
#             tag: latest

# jobs:
#   docker-image:
#     docker:
#       - image: cimg/base:stable
#     steps:
#       - checkout
#       - run: docker version
#       - setup_remote_docker:
#           version: "20.10.11"  # <-- modern Docker version!!
#           docker_layer_caching: true
#       - run: |
#           export DOCKER_BUILDKIT=1
#           docker version
#           docker build .