version: 2.1

#var docker_tag=stlouisn/ubuntu

commands:

  install-docker-buildx:
    steps:
      - run:
          name: Install Docker Buildx
          command: |
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx version
            sudo apt-get update && sudo apt-get install -y binfmt-support qemu-user-static
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker run --privileged --rm tonistiigi/binfmt --install arm64,arm
            docker context create buildcontext
            docker buildx create buildcontext --use

  configure-docker-hub:
    steps:
      - run:
          name: Configure Docker Hub
          command: |
            [ -z "$DOCKER_LOGIN" ] && exit 0
            [ -z "$DOCKER_PASSWORD" ] && exit 0
            docker version
            docker login --username=$DOCKER_LOGIN --password=$DOCKER_PASSWORD

jobs:

  build-multiarch-container:
    environment:
      BUILD_PLATFORMS: "linux/amd64,linux/arm64,linux/arm"
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          #version: 19.03.13
          version: 20.10.11
          docker_layer_caching: true
      - install-docker-buildx
      - configure-docker-hub
      - run:
          name: Build and push container
          no_output_timeout: 2h
          command: |
            docker buildx inspect --bootstrap
            docker buildx build --progress plain --push -t stlouisn/ubuntu --platform linux/amd64,linux/arm64,linux/arm .

workflows:
  version: 2
  build-images:
    jobs:
      - build-multiarch-container:
          name: build-docker-ubuntu
