version: 2.1

orbs:
  docker-buildx: foodles/docker-buildx@0.0.3

workflows:
    build-deploy:
      jobs:
        - docker-buildx/publish:
            dockerfile: dockerfile
            image: stlouisn/ubuntu
            tag: latest