version: 2.1

jobs:
  build-multiarch-container:
    resource_class: medium
    # resource_class: small
    # resource_class: large
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    environment:
      TAG: "stlouisn/ubuntu"
      BUILD_PLATFORMS: "linux/arm64"
      # BUILD_PLATFORMS: "linux/arm64,linux/arm/v7"
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Install Docker Buildx
          command: |
            #mkdir -vp ~/.docker/cli-plugins/
            #curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
            #chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx version
            sudo apt-get update && sudo apt-get install -y binfmt-support qemu-user-static
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker context create buildcontext
            docker buildx create buildcontext --use
      - run:
          name: Configure Docker Hub
          command: |
            [ -z "$DOCKER_LOGIN" ] && exit 0
            [ -z "$DOCKER_PASSWORD" ] && exit 0
            echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_LOGIN --password-stdin
      - run:
          name: Build and push container
          no_output_timeout: 2h
          command: |
            docker buildx inspect --bootstrap
            docker buildx build --progress plain --push -t $TAG --platform $BUILD_PLATFORMS .

workflows:
  version: 2
  build-images:
    jobs:
      - build-multiarch-container:
          name: build-docker-ubuntu
