version: 2.1

jobs:
  build-multiarch-container:
    resource_class: small
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    environment:
      BUILD_PLATFORMS: "linux/arm64,linux/arm/v7"
      C_DESCRIPTION: "ubuntu base image"
      C_MAINTAINER: "stlouisn"
      C_NAME: "ubuntu"
      C_TAG: "latest"
      C_URL: "https://www.ubuntu.com/"
      L_SCHEMA_VERSION: "1.0"
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Configure Docker labels
          command: |
            export BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            bash ./.scripts/get_version.sh
            echo
            echo Labels
            echo ------------------------------------
            echo build_date = $BUILD_DATE
            echo maintainer = $C_MAINTAINER
            echo image_name = $C_NAME:$C_TAG
            echo image_version = $C_VERSION
            pwd
      # - run:
      #     name: Configure Docker Buildx
      #     command: |
      #       docker buildx version
      #       echo
      #       sudo apt-get update -qq && sudo apt-get install -y binfmt-support qemu-user-static
      #       echo
      #       docker pull multiarch/qemu-user-static
      #       echo
      #       docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      #       echo
      #       docker context create buildcontext
      #       echo
      #       docker buildx create buildcontext --use --platform $BUILD_PLATFORMS
      # - run:
      #     name: Configure Docker Hub
      #     command: |
      #       [ -z "$DOCKER_LOGIN" ] && exit 0
      #       [ -z "$DOCKER_PASSWORD" ] && exit 0
      #       echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_LOGIN --password-stdin
      # - run:
      #     name: Build and push container
      #     no_output_timeout: 20m
      #     command: |
      #       docker buildx inspect --bootstrap
      #       echo
      #       docker buildx build --tag $C_MAINTAINER/$C_NAME:$C_TAG --platform $BUILD_PLATFORMS --progress plain --push .

workflows:
  version: 2
  build-container:
    jobs:
      - build-multiarch-container:
          name: build-docker-ubuntu
