version: 2.1

jobs:
  build-multiarch-container:
    resource_class: small
    # resource_class: medium
    # resource_class: large
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    environment:
      IMAGE_TAG: "stlouisn/ubuntu"
      # BUILD_PLATFORMS: "linux/arm64"
      BUILD_PLATFORMS: "linux/arm64,linux/arm/v7"
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Configure Docker Buildx
          command: |
            docker buildx version
            echo
            sudo apt-get update && sudo apt-get install -y -binfmt-support qemu-user-static
            echo
            docker pull multiarch/qemu-user-static
            echo
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            echo
            docker context create buildcontext
            echo
            docker buildx create buildcontext --use --platform $BUILD_PLATFORMS
      - run:
          name: Configure Docker Hub
          command: |
            [ -z "$DOCKER_LOGIN" ] && exit 0
            [ -z "$DOCKER_PASSWORD" ] && exit 0
            echo "$DOCKER_PASSWORD" | docker login --username=$DOCKER_LOGIN --password-stdin
      - run:
          name: Build and push container
          no_output_timeout: 2h
          command: |
            docker buildx inspect --bootstrap
            echo
            docker buildx build --progress plain --push -t $IMAGE_TAG --platform $BUILD_PLATFORMS .

workflows:
  version: 2
  build-container:
    jobs:
      - build-multiarch-container:
          name: build-docker-ubuntu
